# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cli.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Graph(object):
    def setupUi(self, Graph):
        Graph.setObjectName("Graph")
        Graph.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Graph)
        self.centralwidget.setObjectName("centralwidget")
        self.GraphWidget = QtWidgets.QWidget(self.centralwidget)
        self.GraphWidget.setGeometry(QtCore.QRect(10, 10, 771, 541))
        self.GraphWidget.setObjectName("GraphWidget")
        Graph.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Graph)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        Graph.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Graph)
        self.statusbar.setObjectName("statusbar")
        Graph.setStatusBar(self.statusbar)

        self.retranslateUi(Graph)
        QtCore.QMetaObject.connectSlotsByName(Graph)

    def retranslateUi(self, Graph):
        _translate = QtCore.QCoreApplication.translate
        Graph.setWindowTitle(_translate("Graph", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Graph = QtWidgets.QMainWindow()
    ui = Ui_Graph()
    ui.setupUi(Graph)
    Graph.show()
    sys.exit(app.exec_())
