# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cli.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Graph(object):
    def setupUi(self, Graph):
        Graph.setObjectName("Graph")
        Graph.resize(800, 426)
        self.centralwidget = QtWidgets.QWidget(Graph)
        self.centralwidget.setObjectName("centralwidget")
        self.GraphWidget = QtWidgets.QWidget(self.centralwidget)
        self.GraphWidget.setGeometry(QtCore.QRect(410, 10, 371, 361))
        self.GraphWidget.setObjectName("GraphWidget")
        self.DiseaseComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DiseaseComboBox.setGeometry(QtCore.QRect(20, 60, 381, 41))
        self.DiseaseComboBox.setObjectName("DiseaseComboBox")
        self.DemographicsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DemographicsComboBox.setGeometry(QtCore.QRect(20, 240, 381, 41))
        self.DemographicsComboBox.setObjectName("DemographicsComboBox")
        self.DiseaseLabel = QtWidgets.QLabel(self.centralwidget)
        self.DiseaseLabel.setGeometry(QtCore.QRect(20, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DiseaseLabel.setFont(font)
        self.DiseaseLabel.setObjectName("DiseaseLabel")
        self.BarRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.BarRadioButton.setGeometry(QtCore.QRect(20, 160, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BarRadioButton.setFont(font)
        self.BarRadioButton.setObjectName("BarRadioButton")
        self.GeneratePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.GeneratePushButton.setGeometry(QtCore.QRect(120, 330, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.GeneratePushButton.setFont(font)
        self.GeneratePushButton.setObjectName("GeneratePushButton")
        self.PlotTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.PlotTypeLabel.setGeometry(QtCore.QRect(20, 130, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PlotTypeLabel.setFont(font)
        self.PlotTypeLabel.setObjectName("PlotTypeLabel")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(210, 160, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.DemographicsLabel = QtWidgets.QLabel(self.centralwidget)
        self.DemographicsLabel.setGeometry(QtCore.QRect(20, 210, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DemographicsLabel.setFont(font)
        self.DemographicsLabel.setObjectName("DemographicsLabel")
        Graph.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Graph)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        Graph.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Graph)
        self.statusbar.setObjectName("statusbar")
        Graph.setStatusBar(self.statusbar)

        self.retranslateUi(Graph)
        QtCore.QMetaObject.connectSlotsByName(Graph)

    def retranslateUi(self, Graph):
        _translate = QtCore.QCoreApplication.translate
        Graph.setWindowTitle(_translate("Graph", "MainWindow"))
        self.DiseaseLabel.setText(_translate("Graph", "Disease"))
        self.BarRadioButton.setText(_translate("Graph", "Bar Chart"))
        self.GeneratePushButton.setText(_translate("Graph", "Generate"))
        self.PlotTypeLabel.setText(_translate("Graph", "Plot Type Selection"))
        self.radioButton_2.setText(_translate("Graph", "Line Chart"))
        self.DemographicsLabel.setText(_translate("Graph", "Demographics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Graph = QtWidgets.QMainWindow()
    ui = Ui_Graph()
    ui.setupUi(Graph)
    Graph.show()
    sys.exit(app.exec_())
